FIND_PATH(SHAPELIB_INCLUDE_DIR shapefil.h)

FIND_LIBRARY(SHAPELIB_LIBRARY NAMES shp )

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SHAPELIB  DEFAULT_MSG  SHAPELIB_LIBRARY  SHAPELIB_INCLUDE_DIR)

MARK_AS_ADVANCED(SHAPELIB_INCLUDE_DIR SHAPELIB_LIBRARY)

